[general]
theme = "tokyonight"

[games]
[[games.item]]
name = "Steam"
icon = "steam"
command = "steam"

[[games.item]]
name = "Lutris"
icon = "lutris"
command = "lutris"

[[games.item]]
name = "Heroic"
icon = "heroic"
command = "heroic"

[[games.item]]
name = "Minecraft"
icon = "minecraft"
command = "prismlauncher"

[work]
[[work.item]]
name = "Discord"
icon = "discord"
command = "discord"

[[work.item]]
name = "GIMP"
icon = "gimp"
command = "gimp"

[[work.item]]
name = "Krita"
icon = "krita"
command = "krita"

[[work.item]]
name = "Inkscape"
icon = "inkscape"
command = "inkscape"

[webapps]
[[webapps.item]]
name = "YouTube"
icon = "youtube"
url = "https://youtube.com"

[[webapps.item]]
name = "Twitch"
icon = "twitch"
url = "https://twitch.tv"

[[webapps.item]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com"

[[webapps.item]]
name = "ChatGPT"
icon = "chatgpt"
url = "https://chat.openai.com"
