#!/usr/bin/env bash
# === GAMING MODE TOGGLE ===
# WehttamSnaps Niri Setup
# GitHub: https://github.com/Crowdrocker
#
# Toggles between work mode and gaming mode
# Gaming mode: Disables animations, enables performance settings
# Work mode: Restores animations and normal settings

set -euo pipefail

# Configuration
STATE_FILE="$HOME/.cache/wehttamsnaps/gaming-mode-state"
NIRI_CONFIG_DIR="$HOME/.config/niri/"
GAMING_CONFIG="$NIRI_CONFIG_DIR/40-gaming.kdl"
JARVIS_SCRIPT="$HOME/.config/wehttamsnaps/scripts/jarvis-manager.sh"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Create cache directory if it doesn't exist
mkdir -p "$(dirname "$STATE_FILE")"

# Function to show notifications
notify() {
    local title="$1"
    local message="$2"
    local urgency="${3:-normal}"

    if command -v notify-send &> /dev/null; then
        notify-send -u "$urgency" -a "Gaming Mode" "$title" "$message"
    fi
}

# Function to play J.A.R.V.I.S. sound
play_jarvis() {
    local sound="$1"

    if [[ -x "$JARVIS_SCRIPT" ]]; then
        "$JARVIS_SCRIPT" "$sound" &
    fi
}

# Function to check current state
get_state() {
    if [[ -f "$STATE_FILE" ]]; then
        cat "$STATE_FILE"
    else
        echo "off"
    fi
}

# Function to set state
set_state() {
    echo "$1" > "$STATE_FILE"
}

# Function to enable gaming mode
enable_gaming_mode() {
    echo -e "${BLUE}🎮 Enabling Gaming Mode...${NC}"

    # Create gaming config with disabled animations
    cat > "$GAMING_CONFIG" << 'EOF'
// === GAMING MODE CONFIGURATION ===
// Generated by toggle-gamemode.sh
// Disables animations and optimizes for performance

// Disable all animations for maximum FPS
animations {
    slowdown 0.0

    window-open {
        off
    }

    window-close {
        off
    }

    horizontal-view-movement {
        off
    }

    workspace-switch {
        off
    }

    window-resize {
        off
    }
}

// Disable window borders in games
window-rule {
    match app-id="^steam_app_.*$"
    border { off; }
}

// Optimize for gaming performance
prefer-no-csd
EOF

    # Reload Niri configuration
    if command -v niri &> /dev/null; then
        niri msg action reload-config 2>/dev/null || true
    fi

    # Enable CPU performance governor (requires sudo setup)
    if command -v cpupower &> /dev/null && [[ -w /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ]]; then
        echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor > /dev/null 2>&1 || true
    fi

    # Set AMD GPU to high performance (if available)
    if [[ -d /sys/class/drm/card0 ]]; then
        echo "high" | sudo tee /sys/class/drm/card*/device/power_dpm_force_performance_level > /dev/null 2>&1 || true
    fi

    # Disable compositor effects in Noctalia (if supported)
    if command -v qs &> /dev/null; then
        qs -c noctalia-shell ipc call animations disable 2>/dev/null || true
    fi

    # Set state
    set_state "on"

    # Notifications and feedback
    notify "Gaming Mode Enabled" "🎮 Performance optimized\n📊 Animations disabled\n⚡ CPU/GPU at maximum" "normal"
    play_jarvis "gaming"

    echo -e "${GREEN}✓ Gaming Mode Enabled${NC}"
    echo -e "  ${YELLOW}•${NC} Animations: ${RED}DISABLED${NC}"
    echo -e "  ${YELLOW}•${NC} CPU Governor: ${GREEN}Performance${NC}"
    echo -e "  ${YELLOW}•${NC} GPU Mode: ${GREEN}High Performance${NC}"
}

# Function to disable gaming mode (restore work mode)
disable_gaming_mode() {
    echo -e "${BLUE}💼 Disabling Gaming Mode...${NC}"

    # Restore normal config (animations enabled)
    cat > "$GAMING_CONFIG" << 'EOF'
// === GAMING MODE CONFIGURATION ===
// Gaming mode is OFF - animations enabled

// Normal animations (enabled)
animations {
    slowdown 1.0

    window-open {
        duration-ms 200
        curve "ease-out-cubic"
    }

    window-close {
        duration-ms 150
        curve "ease-in-cubic"
    }

    horizontal-view-movement {
        duration-ms 250
        curve "ease-out-cubic"
    }

    workspace-switch {
        duration-ms 200
        curve "ease-out-quad"
    }

    window-resize {
        duration-ms 150
        curve "ease-out-cubic"
    }
}

// Keep game borders disabled for cleaner look
window-rule {
    match app-id="^steam_app_.*$"
    border { off; }
}
EOF

    # Reload Niri configuration
    if command -v niri &> /dev/null; then
        niri msg action reload-config 2>/dev/null || true
    fi

    # Restore CPU governor to schedutil/powersave
    if command -v cpupower &> /dev/null && [[ -w /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ]]; then
        echo "schedutil" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor > /dev/null 2>&1 || \
        echo "powersave" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor > /dev/null 2>&1 || true
    fi

    # Restore AMD GPU to auto mode
    if [[ -d /sys/class/drm/card0 ]]; then
        echo "auto" | sudo tee /sys/class/drm/card*/device/power_dpm_force_performance_level > /dev/null 2>&1 || true
    fi

    # Re-enable compositor effects in Noctalia
    if command -v qs &> /dev/null; then
        qs -c noctalia-shell ipc call animations enable 2>/dev/null || true
    fi

    # Set state
    set_state "off"

    # Notifications and feedback
    notify "Gaming Mode Disabled" "💼 Work mode restored\n✨ Animations enabled\n🔋 Power saving active" "normal"

    echo -e "${GREEN}✓ Gaming Mode Disabled${NC}"
    echo -e "  ${YELLOW}•${NC} Animations: ${GREEN}ENABLED${NC}"
    echo -e "  ${YELLOW}•${NC} CPU Governor: ${BLUE}Balanced${NC}"
    echo -e "  ${YELLOW}•${NC} GPU Mode: ${BLUE}Auto${NC}"
}

# Function to show current status
show_status() {
    local state=$(get_state)

    echo -e "\n${BLUE}═══════════════════════════════════════${NC}"
    echo -e "${BLUE}   WehttamSnaps Gaming Mode Status${NC}"
    echo -e "${BLUE}═══════════════════════════════════════${NC}\n"

    if [[ "$state" == "on" ]]; then
        echo -e "  Status: ${GREEN}ENABLED 🎮${NC}\n"
        echo -e "  ${YELLOW}•${NC} Animations: ${RED}DISABLED${NC}"
        echo -e "  ${YELLOW}•${NC} Performance: ${GREEN}MAXIMUM${NC}"
        echo -e "  ${YELLOW}•${NC} CPU Governor: ${GREEN}Performance${NC}"
        echo -e "  ${YELLOW}•${NC} GPU Mode: ${GREEN}High Performance${NC}"
    else
        echo -e "  Status: ${RED}DISABLED 💼${NC}\n"
        echo -e "  ${YELLOW}•${NC} Animations: ${GREEN}ENABLED${NC}"
        echo -e "  ${YELLOW}•${NC} Performance: ${BLUE}Balanced${NC}"
        echo -e "  ${YELLOW}•${NC} CPU Governor: ${BLUE}Balanced${NC}"
        echo -e "  ${YELLOW}•${NC} GPU Mode: ${BLUE}Auto${NC}"
    fi

    echo -e "\n${BLUE}═══════════════════════════════════════${NC}\n"
}

# Main logic
main() {
    local action="${1:-toggle}"

    case "$action" in
        on|enable)
            enable_gaming_mode
            ;;
        off|disable)
            disable_gaming_mode
            ;;
        toggle)
            local current_state=$(get_state)
            if [[ "$current_state" == "on" ]]; then
                disable_gaming_mode
            else
                enable_gaming_mode
            fi
            ;;
        status)
            show_status
            ;;
        help|--help|-h)
            echo "WehttamSnaps Gaming Mode Toggle"
            echo ""
            echo "Usage: $0 [action]"
            echo ""
            echo "Actions:"
            echo "  toggle          Toggle gaming mode on/off (default)"
            echo "  on, enable      Enable gaming mode"
            echo "  off, disable    Disable gaming mode"
            echo "  status          Show current status"
            echo "  help            Show this help message"
            echo ""
            echo "What Gaming Mode Does:"
            echo "  ✓ Disables all window animations"
            echo "  ✓ Sets CPU to performance governor"
            echo "  ✓ Sets AMD GPU to high performance mode"
            echo "  ✓ Plays J.A.R.V.I.S. notification"
            echo "  ✓ Optimizes for maximum FPS"
            echo ""
            echo "Keybind: Mod+G to toggle"
            ;;
        *)
            echo -e "${RED}Error: Unknown action '$action'${NC}"
            echo "Use '$0 help' for usage information"
            exit 1
            ;;
    esac
}

# Run main function
main "$@"
